[[mgr.prepend_keymap]]
on = "ñ"
run = "leave"
desc = "alternative back"

[[mgr.prepend_keymap]]
on  = "y"
run = [ '''
    shell '/home/morano/.config/yazi/copy uri $@'
''', "yank" ]

[[mgr.prepend_keymap]]
on  = "b"
run = [ '''
    shell '/home/morano/.config/yazi/copy gnome $@'
''', "yank" ]
