[manager]
linemode = "size_and_mtime"

[opener]
volume-view = [
    { run = '/home/morano/Programs/volume-viewer/venv/bin/python /home/morano/Programs/volume-viewer/volume_viewer.py "$@"', orphan = true, for = "unix" },
]

[open]
prepend_rules = [
    { name = "*.nii.gz", use = [ "volume-view", "reveal" ] },
    { name = "*.npy", use = [ "volume-view", "reveal" ] },
    { name = "*.npz", use = [ "volume-view", "reveal" ] },
    { name = "*.dcm", use = [ "volume-view", "reveal" ] },
]
