#!/usr/bin/bash

case $1 in
    volume_up)
        pactl set-sink-volume @DEFAULT_SINK@ +2%
        ;;
    volume_down)
        pactl set-sink-volume @DEFAULT_SINK@ -2%
        ;;
    volume_mute)
        pactl set-sink-mute @DEFAULT_SINK@ toggle
        ;;
    mic_mute)
        pactl set-source-mute @DEFAULT_SOURCE@ toggle
        ;;
    launcher)
        j4-dmenu-desktop --dmenu "dmenu -i -fn 'Fira Code-14'"
        ;;
    web_browser)
        floorp --new-window
        ;;
    alt_web_browser)
        brave --new-window
        ;;
    file_manager)
        if [ -d "/home/morano/SW/" ]
        then
            nautilus --new-window /home/morano/SW/
        else
            nautilus --new-window $HOME
        fi
        ;;
    terminal_file_manager)
        if [ -d "/home/morano/SW/" ]
        then
            wezterm start --always-new-process -e yazi /home/morano/SW/
        else
            wezterm start --always-new-process -e yazi $HOME
        fi
        ;;
    date)
        notify-send -t 2000 "$(date)"
        ;;
    terminal)
        wezterm start --always-new-process
        ;;
    lock)
        i3lock -c 333333
        ;;
    reset_kb_settings)
        xset r rate 200 40
        ;;
    wacom)
        xsetwacom --set "Wacom One by Wacom S Pen stylus" Mode Absolute
        xsetwacom --set "Wacom One by Wacom S Pen eraser" Mode Absolute
        xsetwacom --set "Wacom One by Wacom S Pen stylus" Rotate half
        xsetwacom --set "Wacom One by Wacom S Pen eraser" Rotate half
        xsetwacom --set "Wacom One by Wacom S Pen stylus" MapToOutput next
        xsetwacom --set "Wacom One by Wacom S Pen eraser" MapToOutput next
        ;;
esac
