#!/bin/sh

# ln -s ~/.config/suckless/xprofile ~/.xprofile

xrandr --output HDMI-0 --rotate normal --pos 1440x440 --mode 2560x1440 --rate 75 --primary --output HDMI-1 --mode 2560x1440 --pos 0x0 --rotate right --rate 60
